services:
  mongodb:
    image: mongo:7.0.28
    container_name: sentinel_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: sentinel_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoExpress
      ME_CONFIG_BASICAUTH_PASSWORD: mongoPasswd
    depends_on:
      - mongodb

#===============================
# = ALL REQUIRED VOLUMES
#===============================
volumes:
  mongo_data:
